ErasmusWedding.Web/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ErasmusWedding.Repository;
using ErasmusWedding.Models;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using System.IO;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace ErasmusWedding.net.Controllers
{
    [Produces("application/json")]
    [Route("api/guest")]
    public class GuestController : Controller
    {
		ILogger<GuestController> logger;
		IGuestRepository<Guest> guestRepository;

		public GuestController(IGuestRepository<Guest> guestRepository, ILogger<GuestController> logger)
		{
			this.logger = logger;
			this.guestRepository = guestRepository;
		}

		public async Task<IActionResult> Get()
		{
			try
			{
				logger.LogDebug("Retrieving a list of guests");
				var response = await guestRepository.GetGuests();
				return Ok(new { Guests = response });
			}
			catch (Exception ex)
			{
				logger.LogError(ex, "An error occurred while trying to retrieve the guest list");
				return new ObjectResult("An error occurred trying to retrieve the guest list");
			}
		}
	}
}

ErasmusWedding.Web/Views/Shared/Partials/GuestPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row">
    <div class="col-md-12">
        <h1 class="page-title">Guests</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12" style="margin-bottom:10px">
        <button type="button" class="btn btn-primary-alt">Add Guest</button>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="color:#553895">
                        Guest Name
                    </th>
                    <th style="color:#553895">
                        Guest Email
                    </th>
                    <th style="color:#553895">
                        Invite Date
                    </th>
                    <th style="color:#553895">
                        Rsvp
                    </th>
                    <th style="color:#553895">
                        Rsvp Date
                    </th>
                    <th style="color:#553895">
                        Extra Guests
                    </th>
                    <th style="color:#553895">
                        &nbsp;
                    </th>
                </tr>
            </thead>
            @foreach (var g in Model)
            {
                <tr>
                    <td>
                        @g.Name
                    </td>
                    <td>
                        @g.Email
                    </td>
                    <td>
                        @g.InviteDate
                    </td>
                    <td>
                        @g.Rsvp
                    </td>
                    <td>
                        @g.RsvpDate
                    </td>
                    <td>
                        @g.ExtraGuests
                    </td>
                    <td style="text-align:center">
                        <button type="button" class="btn btn-primary-alt">Send Invite</button>
                    </td>
                </tr>}
        </table>
    </div>
</div>

ErasmusWedding.Web/Views/Shared/Partials/_GuestPartial.cshtml
@model ErasmusWedding.net.Controllers.GuestModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row">
    <div class="col-md-12">
        <h1 class="page-title">Guests</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="color:#553895">
                        Guest Name
                    </th>
                    <th style="color:#553895">
                        Guest Email
                    </th>
                    <th style="color:#553895">
                        Invite Sent
                    </th>
                    <th style="color:#553895">
                        Invite Date
                    </th>
                    <th style="color:#553895">
                        Rsvp
                    </th>
                    <th style="color:#553895">
                        Rsvp Date
                    </th>
                    <th style="color:#553895">
                        Extra Guests
                    </th>
                    <th>
                        &nbsp;
                    </th>
                    <th style="color:#553895">
                        &nbsp;
                    </th>
                    <th style="color:#553895">
                        &nbsp;
                    </th>
                    <th style="color:#553895">
                        &nbsp;
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var g in Model.Guests)
                {
                    <tr>
                        <td style="color:#553895">
                            @g.Name
                        </td>
                        <td style="color:#553895">
                            @g.Email
                        </td>
                        <td style="color:#553895;text-align:center">                            
                            @if (g.InviteSent)
                            {
                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
}
                            else
                            {
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
}
                        </td>
                        <td style="color:#553895">
                            @g.InviteDate
                        </td>
                        <td style="color:#553895;text-align:center">
                            @if (g.Rsvp)
                            {
                                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
}
                            else
                            {
                                <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
}
                        </td>
                        <td style="color:#553895">
                            @g.RsvpDate
                        </td>
                        <td style="color:#553895">
                            @g.ExtraGuests
                        </td>
                        <td style="text-align:center">
                            @Html.ActionLink("Edit", "Guest", new { guestKey = g.GuestKey }, new { @class = "btn btn-primary-alt" })
                        </td>
                        <td style="text-align:center">
                            <a href="@Url.Action("SendInvite", new { guestKey = g.GuestKey })" class="btn btn-primary-alt">Send Invite</a>
                        </td>
                        <td>
                            @Html.ActionLink("Invite Link", "Invite", "Home", new { guestKey = g.GuestKey }, new { @class = "btn btn-primary-alt" })
                        </td>
                        <td>
                            @Html.ActionLink("Rsvp Link", "Index", "Home", new { guestKey = g.GuestKey }, new { @class = "btn btn-primary-alt" })
                        </td>
                    </tr>}
            </tbody>
        </table>
    </div>
    <div class="col-md-3" style="margin-bottom:10px">
        <form asp-controller="Home" asp-action="SaveGuest" method="post">
            @if (Model.Guest != null)
            {
                <div class="form-group">
                    <label for="Name">Guest Name</label>
                    <input type="text" class="form-control" id="Name" name="Name" value="@Model.Guest.Name">
                </div>
                <div class="form-group">
                    <label for="Email">Guest Email</label>
                    <input type="text" class="form-control" id="Email" name="Email" value="@Model.Guest.Email">
                </div>
                <div class="form-group">
                    <label for="InviteSent">Invite Sent</label>
                    <input type="text" class="form-control" id="InviteSent" name="InviteSent" placeholder="InviteSent" readonly value="@Model.Guest.InviteSent.ToString()">
                </div>
                <div class="form-group">
                    <label for="InviteDate">Invite Date</label>
                    <input type="text" class="form-control" id="InviteDate" name="InviteDate" placeholder="Invite Date" readonly>
                </div>
                <div class="form-group">
                    <label for="Rsvp">Rsvp</label>
                    <input type="text" class="form-control" id="Rsvp" name="Rsvp" placeholder="Rsvp" readonly>
                </div>
                <div class="form-group">
                    <label for="RsvpDate">Rsvp Date</label>
                    <input type="text" class="form-control" id="RsvpDate" name="RsvpDate" placeholder="Rsvp Date" readonly>
                </div>
                <div class="form-group">
                    <label for="extraGuests">Extra Guests</label>
                    <input type="text" class="form-control" id="ExtraGuests" name="ExtraGuests" placeholder="ExtraGuests" readonly>
                </div>
                <input type="hidden" name="GuestKey" id="GuestKey" value="@Model.Guest.GuestKey" />
            }
            else
            {
            <!-- Input and Submit elements -->
            <div class="form-group">
                <label for="Name">Guest Name</label>
                <input type="text" class="form-control" id="Name" name="Name" aria-describedby="emailHelp" placeholder="Guest Name">
            </div>
            <div class="form-group">
                <label for="Email">Guest Email</label>
                <input type="text" class="form-control" id="Email" name="Email" placeholder="Guest Email">
            </div>
            <div class="form-group">
                <label for="InviteDate">Invite Date</label>
                <input type="text" class="form-control" id="InviteDate" name="InviteDate" placeholder="Invite Date" readonly>
            </div>
            <div class="form-group">
                <label for="Rsvp">Rsvp</label>
                <input type="text" class="form-control" id="Rsvp" name="Rsvp" placeholder="Rsvp" readonly>
            </div>
            <div class="form-group">
                <label for="RsvpDate">Rsvp Date</label>
                <input type="text" class="form-control" id="RsvpDate" name="RsvpDate" placeholder="Rsvp Date" readonly>
            </div>
            <div class="form-group">
                <label for="extraGuests">Extra Guests</label>
                <input type="text" class="form-control" id="ExtraGuests" name="ExtraGuests" placeholder="ExtraGuests" readonly>
            </div>
            }
            <button type="submit" class="btn btn-primary-alt">Save</button>
        </form>
    </div>
</div>

ErasmusWedding.Web/Views/Shared/Partials/_SongPartial.cshtml
@model ErasmusWedding.net.Controllers.SongModel

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row">
    <div class="col-md-12">
        <h1 class="page-title">Songs</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-9">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th style="color:#553895;width:95%">
                        Song Title
                    </th>
                    <th style="color:#553895">
                        &nbsp;
                    </th>
                </tr>
            </thead>
            @foreach (var g in Model.Songs)
            {
                <tr>
                    <td>
                        @g.SongTitle
                    </td>
                    <td style="text-align:center">
                        @Html.ActionLink("Edit", "Song", new { songKey = g.SongKey }, new { @class = "btn btn-primary-alt" })
                    </td>
                </tr>}
        </table>
    </div>
    <div class="col-md-3" style="margin-bottom:10px">
        <form asp-controller="Home" asp-action="SaveSong" method="post">
            @if (Model.Song != null)
            {
                <div class="form-group">
                    <label for="SongTitle">Song Title</label>
                    <input type="text" class="form-control" id="SongTitle" name="SongTitle" value="@Model.Song.SongTitle">
                </div>
                <input type="hidden" name="SongKey" id="SongKey" value="@Model.Song.SongKey" />
            }
            else
            {
            <!-- Input and Submit elements -->
            <div class="form-group">
                <label for="SongTitle">Song Title</label>
                <input type="text" class="form-control" id="SongTitle" name="SongTitle" placeholder="SongTitle">
            </div>
            }
            <button type="submit" class="btn btn-primary-alt">Save</button>
        </form>
    </div>
</div>